# https://upptime.js.org/docs/configuration
owner: AvantHealth # Your GitHub organization or username, where this repository lives
repo: avant-status # The name of this repository

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/10 * * * *"

sites:
  - name: Avant Health Member Portal
    url: https://app.avanthealth.ai
  - name: Avant Health API
    url: https://app-api.avanthealth.ai

assignees:
  - AvantHealth/infra
status-website:
  theme: light
  cname: status.avanthealth.ai
  logoUrl: https://app.avanthealth.ai/assets/logo-text-0ENtWE94.svg
  name: Avant Health Status
  introTitle: "**Avant Health Platform Status**"
  introMessage: "This is the status website for Avant Health Platform, showing the real-time status of our services. Visit [our website](https://www.avanthealth.ai) for more information about our services."
  favicon: https://app.avanthealth.ai/favicon.ico
  navbar:
    - title: Status
      href: /
    - title: Avant Health
      href: https://www.avanthealth.ai
    - title: Email Support
      href: emailto:support@avanthealth.ai

user-agent: barretthafner
