# https://upptime.js.org/docs/configuration
owner: AvantHealth # Your GitHub organization or username, where this repository lives
repo: avant-status # The name of this repository

sites:
  - name: Avant Health Member Portal
    url: https://app.avanthealth.ai
  - name: Avant Health API
    url: https://app-api.avanthealth.ai

assignees:
  - AvantHealth/infra
status-website:
  cname: status.avanthealth.ai
  logoUrl: https://app.avanthealth.ai/assets/logo-text-0ENtWE94.svg
  name: Avant Health Status
  introTitle: "**Avant Health Platform Status**"
  introMessage: "This is the status website for Avant Health Platform, showing the real-time status of our services. Visit [our website](https://www.avanthealth.ai) for more information about our services."
  favicon: https://app.avanthealth.ai/favicon.ico
